### PR TITLE
add proxy setting.

### PR DESCRIPTION
**Pull request by Doradx**
1. add proxy setting
2. change the function 'pytranscriber.util.MyUtil.is_internet_connected'
3. add requirements.txt

### CODE REVIEW

**Comment by Doradx** [comment]
add a proxy setting dialog for pyTranscriber, just as shown below.
image

**Comment by helloppt211** [comment]
@Doradx 
Nice works for people in China mainland.   
Could you provide a release version on Windows 10?

**Comment by Doradx** [comment]
> @Doradx Nice works for people in China mainland. Could you provide a release version on Windows 10?

You can find it at https://github.com/Doradx/pyTranscriber/releases/tag/v1.5-proxy

**Comment by hbrtv** [comment]
@Doradx 
Can you add a socks5 proxy as well

**Comment by raryelcostasouza** [comment]
@Doradx Sorry for taking time to answer. Looks like a very nice contribution. Thanks a lot. I will study your changes and merge soon if everything fine.

**Comment by mikolaje** [comment]
> @Doradx Sorry for taking time to answer. Looks like a very nice contribution. Thanks a lot. I will study your changes and merge soon if everything fine.

could you also update the Mac version. Many thanks~

**Comment by real-jiakai** [comment]
中国大陆的朋友，可以在这个[Youtube](https://www.youtube.com/watch?v=sX6-iL41ULg)视频中找到解决的方案。 

录制视频要保证声音清晰，不然转出来的文字通篇不对。:smile:

感谢作者开发出这个软件，造福世界。:thumbsup:

**Comment by john-z-huang** [comment]
I want ask, is your google cloud speech api still alive? I mean this String "GOOGLE_SPEECH_API_URL" and "GOOGLE_SPEECH_API_KEY" in this project. I do not get any bytes http response when I using pyTranscriber. Should I set my URL to switch your URL in this project?
thanks for you.
@raryelcostasouza

**Comment by cyberxsboy** [comment]
Error!
Error! Cannot reach Google Speech Servers.

**Review by raryelcostasouza — APPROVED** [review]
Added support for proxies. Thanks for the amazing contribution @Doradx !

**Comment by raryelcostasouza** [comment]
Added support for proxies. Thanks for the great contribution @Doradx !

**Pull request merged**
